# Generated by Django 5.2.8 on 2025-12-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
