# Generated by Django 5.2.8 on 2025-12-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mentor_phone_alter_mentor_bio_alter_mentor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
